/* eslint-disable import/no-dynamic-require */

export default (customIcons: Record<string, any>) => {
    // All icons
    const icons: Record<string, any> = {};

    const steroidsIcons = [
        'add',
        'add_16x16',
        'add_square',
        'arrow_down_18x18',
        'arrow_down_24x24',
        'arrow_drop_down_10x10',
        'arrow_left_18x18',
        'arrow_left_24x24',
        'arrow_right_18x18',
        'arrow_right_24x24',
        'arrow_up_18x18',
        'arrow_up_24x24',
        'long-arrow-alt-down',
        'long-arrow-alt-up',
        'blank',
        'calendar_check',
        'chart',
        'checkmark_12x12',
        'checkmark_8x8',
        'circle_cross_12x12',
        'circle_cross_16x16',
        'circle_cross_18x18',
        'copy',
        'cross_12x12',
        'cross_8x8',
        'default_16x16',
        'default_24x24',
        'done-all_16x16',
        'cut',
        'error_16x16',
        'error_24x24',
        'calendar_range',
        'double_arrow_down',
        'double_arrow_left',
        'double_arrow_right',
        'double_arrow_up',
        'doughnut_chart',
        'edit',
        'expand_down',
        'expand_left',
        'expand_left_double',
        'expand_right',
        'expand_right_double',
        'file_dock',
        'filter',
        'fluid',
        'folder',
        'group',
        'home',
        'img_box',
        'import',
        'export',
        'info_16x16',
        'info_24x24',
        'loading_purple',
        'loading_default',
        'loading_icon_thick',
        'map',
        'menu_dots',
        'menu_left',
        'minis_sq',
        'paste',
        'pie_chart',
        'pin',
        'sad',
        'search',
        'send',
        'setting_line',
        'share',
        'star',
        'success_16x16',
        'success_24x24',
        'support',
        'trash',
        'upload',
        'user',
        'view_hide',
        'warning_16x16',
        'warning_24x24',
        'clip',
        'view',
        'cross_4x4',
        'expand_up',
        'left_12x12',
        'cancel_ellips',
        'facebook',
        'instagram',
        'telegram',
        'vk',
        'whatsapp',
        'burger',
        'sort',
    ];

    steroidsIcons.forEach(iconName => {
        icons[iconName] = require(`./svgs/${iconName}.svg`);
    });

    // Flag icons
    const flagIcons = [
        'ad', 'ae', 'af', 'ag', 'ai', 'al', 'am', 'an', 'ao', 'aq', 'ar', 'as', 'at', 'au', 'aw', 'ax', 'az',
        'ba', 'bb', 'bd', 'be', 'bf', 'bg', 'bh', 'bi', 'bj', 'bl', 'bm', 'bn', 'bo', 'bq', 'br', 'bs', 'bt', 'bv', 'bw', 'by', 'bz',
        'ca', 'cc', 'cd', 'cf', 'cg', 'ch', 'ci', 'ck', 'cl', 'cm', 'cn', 'co', 'cr', 'cu', 'cv', 'cw', 'cx', 'cy', 'cz',
        'de', 'dj', 'dk', 'dm', 'do', 'dz',
        'ec', 'ee', 'eg', 'eh', 'er', 'es', 'et', 'eu',
        'fi', 'fj', 'fk', 'fm', 'fo', 'fr',
        'ga', 'gb', 'gd', 'ge', 'gf', 'gg', 'gh', 'gi', 'gl', 'gm', 'gn', 'gp', 'gq', 'gr', 'gs', 'gt', 'gu', 'gw', 'gy',
        'hk', 'hm', 'hn', 'hr', 'ht', 'hu',
        'id', 'ie', 'il', 'im', 'in', 'io', 'iq', 'ir', 'is', 'it',
        'je', 'jm', 'jo', 'jp',
        'ke', 'kg', 'kh', 'ki', 'km', 'kn', 'kp', 'kr', 'kw', 'ky', 'kz',
        'la', 'lb', 'lc', 'li', 'lk', 'lr', 'ls', 'lt', 'lu', 'lv', 'ly',
        'ma', 'mc', 'md', 'me', 'mf', 'mg', 'mh', 'mk', 'ml', 'mm', 'mn', 'mo', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu', 'mv', 'mw', 'mx', 'my', 'mz',
        'na', 'nc', 'ne', 'nf', 'ng', 'ni', 'nl', 'no', 'np', 'nr', 'nu', 'nz',
        'om',
        'pa', 'pe', 'pf', 'pg', 'ph', 'pk', 'pl', 'pm', 'pn', 'pr', 'ps', 'pt', 'pw', 'py',
        'qa',
        're', 'ro', 'rs', 'ru', 'rw',
        'sa', 'sb', 'sc', 'sd', 'se', 'sg', 'sh', 'si', 'sj', 'sk', 'sl', 'sm', 'sn', 'so', 'sr', 'ss', 'st', 'sv', 'sx', 'sy', 'sz',
        'tc', 'td', 'tf', 'tg', 'th', 'tj', 'tk', 'tl', 'tm', 'tn', 'to', 'tr', 'tt', 'tv', 'tw', 'tz',
        'ua', 'ug', 'um', 'us', 'uy', 'uz',
        'va', 'vc', 've', 'vg', 'vi', 'vn', 'vu',
        'wf', 'ws', 'xk',
        'ye', 'yt', 'za', 'zm', 'zw',
    ];

    flagIcons.forEach(iconName => {
        icons[iconName] = require(`./flags/${iconName}.svg`);
    });

    return {
        ...icons,
        ...customIcons,
    };
};
